SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `crud_simples`;
USE `crud_simples`;

CREATE TABLE `listar_estoque` (
  `id` INT(11) NOT NULL,
  `modelo` VARCHAR(255) NOT NULL,
  `cor` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `listar_estoque` (`id`, `modelo`, `cor`) VALUES
(1, 'Fusca', 'Azul'),
(2, 'Gol', 'Vermelho'),
(3, 'Civic', 'Preto');

ALTER TABLE `listar_estoque`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `listar_estoque`
  MODIFY `id` INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `listar_estoque`
  AUTO_INCREMENT = 4;

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;